# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b2728d5f03672fda654b6071f6046324665b9e00df3895d13488a7cc7ea082549c472e6d3d1d2e922ea9d64a22b6ced5ad601171bb8685c694253c3d11ee60e

test:
  secret_key_base: 6c0c61fad4a26896485f939f7871cfb831534d1b623641ecc63057b23884ce8e084da87563f09d90a0c838991344b9e5083edb0e35221469b3766345a9a5d95d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
